create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'analista' check (role in ('super_admin','admin','analista')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id text primary key,
  name text not null,
  title text not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  campaign_id text not null default 'carrito-abandonado',
  cart_id text,
  order_id text,
  email text,
  store text,
  seller text,
  reason_code text not null,
  reason_label text not null,
  other_text text,
  user_agent text,
  created_at timestamptz not null default now()
);

insert into public.campaigns (id, name, title, description)
values (
  'carrito-abandonado',
  'Carrito abandonado',
  'Queremos conocer tu experiencia',
  'Encuesta para entender los motivos de abandono en checkout.'
)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.campaigns enable row level security;
alter table public.survey_responses enable row level security;

drop policy if exists "public can insert survey responses" on public.survey_responses;
create policy "public can insert survey responses"
on public.survey_responses for insert
to anon, authenticated
with check (true);

drop policy if exists "authenticated can read survey responses" on public.survey_responses;
create policy "authenticated can read survey responses"
on public.survey_responses for select
to authenticated
using (true);

drop policy if exists "authenticated can read campaigns" on public.campaigns;
create policy "authenticated can read campaigns"
on public.campaigns for select
to authenticated, anon
using (active = true);

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);
