-- 1) Tabla para guardar respuestas
create table if not exists public.encuesta_carritos (
  id bigint generated by default as identity primary key,
  cart_id text,
  order_id text,
  email text,
  tienda text,
  seller text,
  motivo text not null,
  motivo_texto text,
  user_agent text,
  created_at timestamp with time zone default now()
);

-- 2) Seguridad RLS
alter table public.encuesta_carritos enable row level security;

-- 3) Los clientes pueden insertar respuestas desde la encuesta publica
drop policy if exists "clientes insertan respuestas" on public.encuesta_carritos;
create policy "clientes insertan respuestas"
on public.encuesta_carritos
for insert
to anon
with check (true);

-- 4) Solo usuarios logueados en Supabase Auth pueden leer el panel administrador
drop policy if exists "admin lee respuestas" on public.encuesta_carritos;
create policy "admin lee respuestas"
on public.encuesta_carritos
for select
to authenticated
using (true);

-- Opcional: permitir borrar registros desde futuras versiones del panel
-- drop policy if exists "admin borra respuestas" on public.encuesta_carritos;
-- create policy "admin borra respuestas"
-- on public.encuesta_carritos
-- for delete
-- to authenticated
-- using (true);
